### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by bidspells** [rkaradas/MaPerWiki#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [MaPerWiki](https://github.com/rkaradas/MaPerWiki) package 0.1.11

### Stack Trace

Uncaught TypeError: Cannot read property 'removeChild' of null

```
At /Users/kamsties/.atom/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:1221

TypeError: Cannot read property 'removeChild' of null
    at remove (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:1221:16)
    at /packages/MaPerWiki/node_modules/vue/dist/vue.common.js:1065:5
    at applyTransition (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:1093:5)
    at removeWithTransition (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:1064:3)
    at /packages/MaPerWiki/node_modules/vue/dist/vue.common.js:8482:3)
    at Directive.remove (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:8985:12)
    at Directive.diff (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:8798:14)
    at Directive.update (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:8704:10)
    at Vue._update (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:12986:15)
    at Watcher.run (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:8004:17)
    at runBatcherQueue (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:7735:13)
    at Array.flushBatcherQueue (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:7705:5)
    at MutationObserver.nextTickHandler (/packages/MaPerWiki/node_modules/vue/dist/vue.common.js:440:16)
```

### Commands

```
     -0:51.7.0 markdown-preview-enhanced:toggle (span.invisible-character.eol)
     -0:42.6.0 MaPerWiki:toggleWikiSearch (input.hidden-input)
     -0:35.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
language-pfm 0.82.0 
MaPerWiki 0.1.11 
markdown-preview-enhanced 0.10.8 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
pdf-view 0.55.0 
process-palette 0.12.0 
split-diff 1.2.0 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.2.0 
```

**Comment by rkaradas** [comment]
Issue should be fixed in 0.1.13. The problem was, that there were duplicate entries in the results array (WikiSearch). 
Can you confirm that it's working now? Thanks.
